
---
- name: httpd-efs-docker.yml 
#- Ansible playbook to run httpd container as www (uid 2000) with EFS mount
  hosts: all
  become: yes

  vars:
    efs_web_dir: /mnt/efs/www
    www_uid: 2000
    www_user: www


  environment:
    DOCKER_HOST: unix:///var/run/docker.sock
  tasks:
    - name: Ensure www user exists with UID 2000
      user:
        name: "{{ www_user }}"
        uid: "{{ www_uid }}"
        shell: /bin/bash
        create_home: yes

    - name: Create EFS web directory
      file:
        path: "{{ efs_web_dir }}"
        state: directory
        owner: "{{ www_user }}"
        group: "{{ www_user }}"
        mode: '0755'

    - name: Ensure www user exists with UID 2000
      user:
        name: "{{ www_user }}"
        uid: "{{ www_uid }}"
        shell: /bin/bash
        create_home: yes

    - name: Create EFS web directory
      file:
        path: "{{ efs_web_dir }}"
        state: directory
        owner: "{{ www_user }}"
        group: "{{ www_user }}"
        mode: '0755'

    - name: Add Docker CE repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo

    - name: Install Docker CE and dependencies
      dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        allowerasing: yes

    - name: Install docker-py
      pip:
        name: docker-py

    - name: Install requests version 2.3 for Python
      pip:
        name: requests==2.31.0
        executable: pip3


    - name: Reload systemd daemon for Docker
      systemd:
        daemon_reload: yes

    - name: Start and enable Docker
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes      

    - name: Copy Dockerfile to target
      copy:
        src: ./docker-httpd/Dockerfile
        dest: /home/{{ ansible_user | default('ec2-user') }}/Dockerfile
        mode: '0644'

    - name: Copy docker-compose.yml to target
      copy:
        src: ./docker-httpd/docker-compose.yml
        dest: /home/{{ ansible_user | default('ec2-user') }}/docker-compose.yml
        mode: '0644'

    - name: Run docker compose up
      shell: |
        cd /home/{{ ansible_user | default('ec2-user') }}
        docker compose up -d
      args:
        executable: /bin/bash
      environment:
        DOCKER_HOST: unix:///var/run/docker.sock
      become: yes

